### ISSUE TITLE
BR 4.0.9 is incompatible with 4.0.8 when using GCS to store backup

### ISSUE THREAD

**Issue by overvenus** [pingcap/br#675]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?

Backup TiDB to GCS with a URL has no tail '/' via BR 4.0.8.
Restore TiDB from GCS.

2. What did you expect to see?

Restore success.

3. What did you see instead?

Restore fails.

------------

This incompatibility is caused by https://github.com/pingcap/br/pull/647. We need to add a fullback to compatible with older backup (<=4.0.8)

**Comment by kennytm** [comment]
The bug fixed by #647 has two effects.

1. If the storage is set as `gcs://bucket/prefix`, the SSTs are written correctly to `gcs://bucket/prefix/*.sst` but the backupmeta is written wrongly to `gcs://bucket/prefixbackupmeta`.
2. If the storage is set as `gcs://bucket/prefix/`, the backupmeta is written correctly to `gcs://bucket/prefix/backupmeta`, but the SSTs are written wrongly to `gcs://bucket/prefix//*.sst` (note the extra slash).

Case 1 can be supported simply by adding a `--backupmeta-file` flag to specify an alternative path of the backupmeta.

Case 2 is hard to fix when #647 is in effect since we Trim() all slashes, meaning `-s gcs://bucket/prefix//` is equivalent to `-s gcs://bucket/prefix`, and it won't let TiKV find `gcs://bucket/prefix//*.sst`.

**Comment by kennytm** [comment]
Moving (renaming) objects in GCS: https://cloud.google.com/storage/docs/gsutil/commands/mv

Like S3, moving is equivalent to Copy + Delete and is not free.
